version: '2'
services:
    pdftest-app:
        image: pdftest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pdftest-mysql:3306/pdftest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pdftest-mysql:
        extends:
            file: mysql.yml
            service: pdftest-mysql
